### ISSUE TITLE
Login screen color in dark theme

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#1]
When mobile is in dark theme mode, login screen background color changed to black

![Screenshot_20231130_164902](https://github.com/antonym8/Team-app/assets/142376069/8522d653-d1a4-402f-af21-d66db1d168e8)

**Comment by m8brindakumar** [comment]
Its fixed/Changed.. this id Day night theme dark mode users can use this theme but i changed .

**Comment by m8brindakumar** [comment]
Its fixed .

**Comment by antonym8** [comment]
![Screenshot_20231229_124737](https://github.com/antonym8/Team-app/assets/142376069/4eb35a30-46fd-4b1f-b417-7d8c42ad494d)
