### ISSUE TITLE
Delete volunteers functionality not working

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#11]
Delete volunteer button not working

![Screenshot_20231130_170307](https://github.com/antonym8/Team-app/assets/142376069/7677619c-b490-43ae-8be4-5b0a88840814)

**Comment by m8brindakumar** [comment]
fixed. remove that text, please long press the cared it enable the delete button and it can be deleted.

**Comment by m8brindakumar** [comment]
its working
