### ISSUE TITLE
Religion -> Picture not displayed

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#110]
![Screenshot_20240202_102827](https://github.com/antonym8/Team-app/assets/142376069/b443e620-aad5-440d-b47d-2c090cc00a64)

**Comment by m8brindakumar** [comment]
its working

**Comment by antonym8** [comment]
Not working 

https://github.com/antonym8/Team-app/assets/142376069/1801342a-c8cd-4b6f-b2c8-2123a2c3bb8e

**Comment by m8brindakumar** [comment]
Fixed
