### ISSUE TITLE
Volunteer -> two delete options

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#120]
One delete option asks delete confirmation and another option deletes the volunteer without confirmation message

https://github.com/antonym8/Team-app/assets/142376069/41ebb029-2fcc-47f8-aa83-94cae0fab1f8

https://github.com/antonym8/Team-app/assets/142376069/2645f807-f1fd-483d-9e69-10d372dc1bd0

**Comment by m8brindakumar** [comment]
Fixed. One delete option is enabled with inside the voter details
