### ISSUE TITLE
Add banner -> accepts other size images too

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#124]
Can able to upload other size images too

![Screenshot_20240202_111633](https://github.com/antonym8/Team-app/assets/142376069/52bd8c8f-1e6e-47bb-b1b5-89bd43e2b2c5)

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
It shows error message even after upload correct file size

![Screenshot_20240306_115951](https://github.com/antonym8/Team-app/assets/142376069/6e84f6ff-808d-4915-9436-a39de3ff29b2)

![Screenshot_20240306_115941](https://github.com/antonym8/Team-app/assets/142376069/18c80a01-8e98-4a71-aaef-d7a8e425577b)

**Comment by m8brindakumar** [comment]
fixed
