### ISSUE TITLE
Volunteer -> Edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#13]
Error message displayed when edit the volunteer

![Screenshot_20231214_125757](https://github.com/antonym8/Team-app/assets/142376069/541bc539-3a6f-48dc-958b-e6d0f9dba8a4)

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
https://github.com/antonym8/Team-app/assets/142376069/b9143e90-9136-47f9-896f-abf03ded5871
