### ISSUE TITLE
Login -> back button

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#14]
Splash screen displayed when click back button from login page

![Screenshot_20231130_170717](https://github.com/antonym8/Team-app/assets/142376069/e36b6a94-cf98-49d8-b1a5-2447bee3100c)

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
https://github.com/antonym8/Team-app/assets/142376069/3a96daf8-fa7f-4184-9650-c082b87f4652

**Comment by antonym8** [comment]
https://github.com/antonym8/Team-app/assets/142376069/5ee56b77-8875-40cc-aeb6-c3cd330f6204

**Comment by m8brindakumar** [comment]
fixed
