### ISSUE TITLE
Change password -> Incorrect current password

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#159]
New password updated when enter incorrect current password

https://github.com/antonym8/Team-app/assets/142376069/06d73751-7511-4fee-94aa-95fda2510b68

**Comment by antonym8** [comment]
Entered correct current password but toast message displayed "Current password is wrong"

![Screenshot_20240222_161521](https://github.com/antonym8/Team-app/assets/142376069/5c4b2c54-82eb-47f5-92bc-42fc9d794b49)

**Comment by m8brindakumar** [comment]
its working, kidly check properly
