### ISSUE TITLE
Survey -> Null value

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#179]
![Screenshot_20240220_151308](https://github.com/antonym8/Team-app/assets/142376069/7fa315a8-ac63-46bf-9176-d2f516063ee3)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
Null value when create voter without fill relation name

![Screenshot_20240222_155648](https://github.com/antonym8/Team-app/assets/142376069/45690f59-e157-4641-9700-ad14ecb6a51f)

**Comment by m8brindakumar** [comment]
Fixed
