### ISSUE TITLE
Religion & Caste edit data -> shows religion caste add page

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#184]
1. Edit data shows add religion & caste page
2. Caste created with already existing name

https://github.com/antonym8/Team-app/assets/142376069/b6db63f1-2f73-4f51-a047-3df4f8268fef

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
No error message displayed when create new with existing name


https://github.com/antonym8/Team-app/assets/142376069/b325f7d4-d597-446a-9887-556f3d1b8ffe

**Comment by m8brindakumar** [comment]
Fixed
