### ISSUE TITLE
Multiple booth number and text cut off

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#192]
![Screenshot_20240222_182017](https://github.com/antonym8/Team-app/assets/142376069/d61c969d-dd4d-4015-87cd-e5f841830332)

**Comment by m8brindakumar** [comment]
fIxed, and also check with back end response

**Comment by antonym8** [comment]
Still booth number shows multiple times

![Screenshot_20240229_095957](https://github.com/antonym8/Team-app/assets/142376069/b6e97821-ed79-41ea-97a6-3d0f212c5b41)

**Comment by m8brindakumar** [comment]
its working
