### ISSUE TITLE
Profile picture placeholder

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#20]
First time dummy profile picture should display as a placeholder

![Screenshot_20231214_122337](https://github.com/antonym8/Team-app/assets/142376069/5a24dab7-4cb9-49a0-8589-607d1b34eff6)

**Comment by m8brindakumar** [comment]
its fixed

**Comment by antonym8** [comment]
![Screenshot_20231227_161136](https://github.com/antonym8/Team-app/assets/142376069/c4e81b39-08b9-466f-8cc6-ea4d79b9cfc6)
