### ISSUE TITLE
Add volunteer -> click add volunteer button after error message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#205]
Steps to reproduce:
1. Fill all fields without select the responsibilities checkbox and click add volunteer button
2. Responsibilities list should not empty error message should display
3. Then select the checkbox and click add volunteer button
4. Now it shows service temporarily unavailable error message

![Screenshot_20240306_125141](https://github.com/antonym8/Team-app/assets/142376069/0e30137e-607d-4675-bf3c-95303cf135c9)

**Comment by m8brindakumar** [comment]
Fixed
