### ISSUE TITLE
Profile picture not displayed in side menu

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#21]
After update the profile picture it's not displayed in side menu. It's displayed only after logout and login to the application

![Screenshot_20231215_125404](https://github.com/antonym8/Team-app/assets/142376069/c23e04ed-d4d4-46b9-a681-e8c8b37bd70b)

**Comment by m8brindakumar** [comment]
its working

**Comment by antonym8** [comment]
Not fixed


https://github.com/antonym8/Team-app/assets/142376069/6f150918-3a32-4d14-809e-395b34dd5346

**Comment by antonym8** [comment]
After update the profile picture, page redirects to dashboard.

**Comment by m8brindakumar** [comment]
its working

**Comment by m8brindakumar** [comment]
fixed
