### ISSUE TITLE
Add volunteer -> with blank data

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#22]
Proper validation message should display when add volunteer with blank data

![Screenshot_20231214_125323](https://github.com/antonym8/Team-app/assets/142376069/6692f300-274d-4df5-8587-db3642b9cd1b)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
![Screenshot_20240111_122452](https://github.com/antonym8/Team-app/assets/142376069/857448bb-e775-4955-b8c1-d455540290be)
