### ISSUE TITLE
Expiry date calendar after select the date

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#25]
Calendar should indicates the selected date and expiry date field should display 2 digit numbers for date and month

![Screenshot_20231214_125757](https://github.com/antonym8/Team-app/assets/142376069/e2b34083-9048-447c-b0f9-cc030e9dde18)

![Screenshot_20231215_144343](https://github.com/antonym8/Team-app/assets/142376069/227d93cd-8985-4bce-b4b5-f5c4e27962d8)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
Not fixed

**Comment by m8brindakumar** [comment]
its working

**Comment by antonym8** [comment]
Selected the 30th may from calendar and when click on date field the calendar indicates the current date

**Comment by m8brindakumar** [comment]
its working
