### ISSUE TITLE
Add volunteer -> Volunteer status after create new volunteer

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#26]
After create new volunteer page should redirect to list page and create volunteer should be in active state

![Screenshot_20231214_125616](https://github.com/antonym8/Team-app/assets/142376069/a44ee37a-9f99-48d4-b8aa-7bf063da5657)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
After create volunteer, page should redirect to volunteers list page but now it redirected to dashboard

**Comment by antonym8** [comment]
Service temporarily unavailable error message displayed when create new volunteer with valid data

**Comment by m8brindakumar** [comment]
its working
