### ISSUE TITLE
Delete volunteer after edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#29]
Blank screen displayed when delete the volunteer after edit

Steps to reproduce:
1. Edit volunteer
2. Click back button
3. Delete volunteer

![Screenshot_20231214_153447](https://github.com/antonym8/Team-app/assets/142376069/e807e5d6-19bd-40a1-910e-23a17973445c)

**Comment by m8brindakumar** [comment]
its fixed and working fine please check it the updated build
