### ISSUE TITLE
Not able to change the status of 4th volunteer and below volunteers

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#30]
Status updated successfully message displayed but status not changed

![Screenshot_20231214_125616](https://github.com/antonym8/Team-app/assets/142376069/04401a4e-6bf5-47e1-8cff-7c15f477ae7a)

**Comment by m8brindakumar** [comment]
its fixed , type mismatching scenario we already fixed

**Comment by antonym8** [comment]
https://github.com/antonym8/Team-app/assets/142376069/b49dcc3a-d0fd-4e89-b948-ba0ab4b09cb8
