### ISSUE TITLE
Double tap on volunteer

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#31]
Application should not allow double tap but now multiple volunteer info popup opened when double tap the volunteer

![Screenshot_20231215_161449](https://github.com/antonym8/Team-app/assets/142376069/e681354d-c403-4b2c-a5fd-f8a77c1ce7fa)
![Screenshot_20231215_161453](https://github.com/antonym8/Team-app/assets/142376069/7c7012c8-502c-4732-9a88-50123e07a962)
![Screenshot_20231215_161458](https://github.com/antonym8/Team-app/assets/142376069/52108805-3192-4a79-93c6-2a7699f93266)

**Comment by m8brindakumar** [comment]
Fixed
