### ISSUE TITLE
Volunteers list -> Overlapping button

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#32]
Add volunteer and delete volunteers buttons are overlapped over the volunteers list

![Screenshot_20231214_165119](https://github.com/antonym8/Team-app/assets/142376069/9ea96b44-0c66-4a5b-b32d-b18155db65fe)

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
![Screenshot_20231229_124539](https://github.com/antonym8/Team-app/assets/142376069/21bbdbf9-ae32-4bcb-8b37-637f0983392f)
