### ISSUE TITLE
Close the app

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#34]
When close the app, session expired and it logged out automatically

https://github.com/antonym8/Team-app/assets/142376069/ed8f1c6c-eb6c-4613-aca0-c78d87b630dd

**Comment by m8brindakumar** [comment]
Okay, it's fixed. During the development phase, we frequently switched between the local and staging environments, resulting in different tokens. This required us to log in repeatedly. After addressing this issue, we have now disabled this functionality, and the problem is resolved.

**Comment by antonym8** [comment]
https://github.com/antonym8/Team-app/assets/142376069/78d91524-2422-47d2-bb7c-e9e8cbab9722
