### ISSUE TITLE
Download voter list

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#35]
Voter list downloaded in pdf format and it's showing error. It should be downloaded in xlsx or csv format.

![Screenshot_20231221_152456](https://github.com/antonym8/Team-app/assets/142376069/038264a0-5385-4f30-a8e3-15d0459c8328)

**Comment by m8brindakumar** [comment]
its working, once again i will check it and update you

**Comment by m8brindakumar** [comment]
its working

**Comment by antonym8** [comment]
Not fixed

https://github.com/antonym8/Team-app/assets/142376069/8a324029-e78a-47dc-b1b3-42b7d850041f

**Comment by m8brindakumar** [comment]
Fixed
