### ISSUE TITLE
Add voter -> DOB field

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#37]
Now DOB field showing as a text field it should be date field

![Screenshot_20231221_154854](https://github.com/antonym8/Team-app/assets/142376069/a85673c0-8b52-4f75-bbca-881d22362392)

**Comment by m8brindakumar** [comment]
its fixed

**Comment by antonym8** [comment]
![Screenshot_20231229_125756](https://github.com/antonym8/Team-app/assets/142376069/0be3b7d0-1b2d-4431-9c9e-540f7fbfc4a5)
