### ISSUE TITLE
Add voter -> Relation type and gender field toast message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#38]
When select relation type and gender field, selected relation type and gender are showing in the toast message

![Screenshot_20231221_155831](https://github.com/antonym8/Team-app/assets/142376069/43e849ef-7ee2-4434-b9b4-1e4d09c87531)
![Screenshot_20231221_155853](https://github.com/antonym8/Team-app/assets/142376069/e621ce1c-7b98-4733-b13b-75242586c756)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
![Screenshot_20231229_124417](https://github.com/antonym8/Team-app/assets/142376069/bd0f35b3-76c1-48e8-8e8c-00800937e77c)
