### ISSUE TITLE
Add voter without religion and caste

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#40]
Service temporarily unavailable error message displayed

![Screenshot_20231221_160026](https://github.com/antonym8/Team-app/assets/142376069/bf95c094-bd1d-495d-bb51-1546227d0c20)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
https://github.com/antonym8/Team-app/assets/142376069/1d21c82a-0e6e-434a-bd50-fc75472cc7ac
