### ISSUE TITLE
Add voter with numeric value in name fields

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#41]
Voter created with numeric value in name field

![Screenshot_20231221_160147](https://github.com/antonym8/Team-app/assets/142376069/b5624ece-3d70-4fa1-901a-51fbf44d80f6)

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
Last name field accepts the numeric value

https://github.com/antonym8/Team-app/assets/142376069/3d9e2d7b-dd0e-4cc6-a369-9e4b9c2aeab7

**Comment by m8brindakumar** [comment]
fixed
