### ISSUE TITLE
Add voter with invalid mobile number

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#42]
Mobile number filed should accepts only 10 digits number

![Screenshot_20231222_102253](https://github.com/antonym8/Team-app/assets/142376069/2ac00b58-36db-4f44-b359-ef36c03055ff)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
https://github.com/antonym8/Team-app/assets/142376069/a9588a1a-2608-445a-8c58-89718f097024
