### ISSUE TITLE
Search voter

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#45]
Search option not working

![Screenshot_20231221_160331](https://github.com/antonym8/Team-app/assets/142376069/23adc046-6fb4-4c46-b492-f6a852bac619)

**Comment by m8brindakumar** [comment]
It's working because the design work for the search and filter module is completed. However, the functional module is not yet finished, which is why the app is crashing. I will complete the module in the next milestone.

**Comment by m8brindakumar** [comment]
its working

**Comment by antonym8** [comment]
Not able to search voter with voter id
If no records found means, it should display No records found message but now it displayed blank

https://github.com/antonym8/Team-app/assets/142376069/c9a29bb7-e5eb-40c4-9bf6-0b329959e8c0
