### ISSUE TITLE
Update voters availability with valid data

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#47]
Checkboxes id numbers are displayed in toast message

![Screenshot_20231222_105819](https://github.com/antonym8/Team-app/assets/142376069/c0930254-11d9-4ea5-96d0-38c7c7b5df05)

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
https://github.com/antonym8/Team-app/assets/142376069/f848b420-4248-4e2e-a1aa-9fdeb0956f22
