### ISSUE TITLE
Religion & Caste -> Religion icon is missing

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#48]
![Screenshot_20231222_105841](https://github.com/antonym8/Team-app/assets/142376069/99252ae5-b320-408c-bd71-4f259484af37)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
![Screenshot_20240111_154926](https://github.com/antonym8/Team-app/assets/142376069/bbc2ade8-b9b0-4224-b47e-86d1f6dbe14c)
