### ISSUE TITLE
Add voter availability button is missing

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#49]
Add voter availability button is missing

![Screenshot_20231222_174505](https://github.com/antonym8/Team-app/assets/142376069/ef19733b-6044-442c-b12c-305a705506e7)

**Comment by m8brindakumar** [comment]
Voters Availability is only came from masters, No CRUD functions

**Comment by m8brindakumar** [comment]
Voters Availability is only came from masters, No CRUD functions

**Comment by antonym8** [comment]
![Screenshot_20240111_125306](https://github.com/antonym8/Team-app/assets/142376069/675e6938-92b9-42bc-83e1-c95a9f0a1edd)
