### ISSUE TITLE
Add volunteer -> Select booth field

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#5]
Select booth field should be a dropdown but now it's showing as a text field

![Screenshot_20231130_170040](https://github.com/antonym8/Team-app/assets/142376069/680a2342-4681-42ba-a8cb-ee465222e669)

**Comment by m8brindakumar** [comment]
its working

**Comment by antonym8** [comment]
![Screenshot_20231229_124856](https://github.com/antonym8/Team-app/assets/142376069/25f4c9b0-1c56-451d-a9bd-354dae2870c3)
