### ISSUE TITLE
Add religion & caste with blank data

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#50]
Service temporarily unavailable error message displayed

![Screenshot_20231222_105924](https://github.com/antonym8/Team-app/assets/142376069/8a3a7332-2b98-4bd5-81c5-ec3e1b336d30)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
![Screenshot_20240111_125521](https://github.com/antonym8/Team-app/assets/142376069/a8445c47-d9ed-4158-97a9-eee39d695ed2)
