### ISSUE TITLE
Add religion & Caste -> Submit without enter caste name

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#51]
Created with blank caste name

https://github.com/antonym8/Team-app/assets/142376069/afa6f242-0bb3-45d7-a263-295be55fb9e5

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
![Screenshot_20240111_125521](https://github.com/antonym8/Team-app/assets/142376069/0477fca0-f4cb-4cac-bbde-4244226dcb1a)
