### ISSUE TITLE
Edit religion & Caste

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#53]
Edit button is missing

![Screenshot_20231222_105841](https://github.com/antonym8/Team-app/assets/142376069/9ae07501-159a-4bd1-b9a1-bcdd18eaf2ed)

**Comment by m8brindakumar** [comment]
its fixed. its changed

**Comment by antonym8** [comment]
Edit button redirects to add religion & caste page

https://github.com/antonym8/Team-app/assets/142376069/b3431484-4846-4637-b0b0-4b5af59249f5

**Comment by m8brindakumar** [comment]
Fixed
