### ISSUE TITLE
Parties -> Remove data

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#55]
Remove data button is not working

![Screenshot_20231222_111743](https://github.com/antonym8/Team-app/assets/142376069/14c1e2bc-f2ba-4b66-acd3-b344c9e15984)

**Comment by m8brindakumar** [comment]
Fixed

**Comment by m8brindakumar** [comment]
It removes the text 'remove data' due to some UI issues and adds the 'delete' and 'edit' buttons on the list page.

**Comment by antonym8** [comment]
Spelling mistake in 'Party'

![Screenshot_20231229_110348](https://github.com/antonym8/Team-app/assets/142376069/95abe5ee-514d-45c5-8f1f-d09fee117a14)

**Comment by antonym8** [comment]
![Screenshot_20240111_130159](https://github.com/antonym8/Team-app/assets/142376069/d292287b-613f-474b-9323-ea69323e039f)
