### ISSUE TITLE
Add party without add symbol

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#56]
Something went wrong error message displayed

![Screenshot_20231222_111840](https://github.com/antonym8/Team-app/assets/142376069/8147ccb2-b251-4685-9ff2-5a3942d57235)

**Comment by m8brindakumar** [comment]
Yes, a party symbol is mandatory. Without a symbol, it is not allowed to create a party. So, the message says, 'Something is wrong, please add/check the image.
