### ISSUE TITLE
Uploaded image location should not display

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#57]
![Screenshot_20231222_111939](https://github.com/antonym8/Team-app/assets/142376069/7886c5d0-e848-4d9d-8acd-93490df3228d)

**Comment by m8brindakumar** [comment]
Okay, sure. In this development phase, I need a storage location for some clarification. That's why I am using it. i will remove on it.

**Comment by antonym8** [comment]
![Screenshot_20240123_110207](https://github.com/antonym8/Team-app/assets/142376069/b4c032d6-c4ca-44cf-84f1-7a1cc17345c5)
