### ISSUE TITLE
Add party button hides the data

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#58]
![Screenshot_20231222_155843](https://github.com/antonym8/Team-app/assets/142376069/20ee97c3-4ad6-4e97-a91e-2ce3145b7de8)

**Comment by m8brindakumar** [comment]
UI issue fixed

**Comment by antonym8** [comment]
![Screenshot_20231229_130042](https://github.com/antonym8/Team-app/assets/142376069/1341ba48-7558-4b6b-ad09-bb82d745e5dd)
