### ISSUE TITLE
Add party -> Spelling mistake in toast message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#59]
Spelling should be 'Party' not 'partie'

![Screenshot_20231222_155929](https://github.com/antonym8/Team-app/assets/142376069/d0b9e12b-5aca-44af-bb4c-816952619f94)

**Comment by m8brindakumar** [comment]
Ok ,it is response message will change it

**Comment by antonym8** [comment]
![Screenshot_20240111_154720](https://github.com/antonym8/Team-app/assets/142376069/fe860e5a-fac2-4de7-a551-fc0343b9bc25)
