### ISSUE TITLE
Login using mobile number -> Enter letters in mobile number field

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#60]
Mobile number field should not allow to enter letter.

https://github.com/antonym8/Team-app/assets/142376069/1ca4ca99-ca99-42bd-9300-2e0c7064c1fb

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
![Screenshot_20240111_120228](https://github.com/antonym8/Team-app/assets/142376069/117ccf21-7a50-478d-8039-42dacead9531)
