### ISSUE TITLE
Login using mobile number -> Enter more than 10 digit number

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#61]
Mobile number field should not allow user to enter more than 10 digits number

https://github.com/antonym8/Team-app/assets/142376069/ed2a7d60-6344-4e96-a01d-17b95f8c1c19

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
https://github.com/antonym8/Team-app/assets/142376069/63ec8b89-869b-4482-be0a-abe85e8dcf04
