### ISSUE TITLE
Verify with OTP page UI issue

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#62]
Edit and Resend buttons spacing is different from the design

![Screenshot_20231227_154402](https://github.com/antonym8/Team-app/assets/142376069/74ee90a3-d13e-4b3e-83dc-8142e423a2d9)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
![Screenshot_20240111_154542](https://github.com/antonym8/Team-app/assets/142376069/d743c5f2-2a88-4243-88cc-454c15bfd7f0)
