### ISSUE TITLE
Verify with OTP -> Edit mobile number

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#63]
Edit button not working

![Screenshot_20231227_154806](https://github.com/antonym8/Team-app/assets/142376069/4b731ede-9582-4819-a657-7dec9ddc1ced)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
https://github.com/antonym8/Team-app/assets/142376069/25f9c2d3-a3be-4c61-9f10-922f5f31ec2d
