### ISSUE TITLE
Verify with OTP -> Clicking on 'Go to home' button redirects to dashboard without proper login

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#65]
https://github.com/antonym8/Team-app/assets/142376069/c8d2bd21-e100-4ba7-b3cc-43c3fb194fd4

**Comment by m8brindakumar** [comment]
SMS gateway not integarted, thats why go properly...it will be complete on next lilestone

**Comment by m8brindakumar** [comment]
working
