### ISSUE TITLE
Settings -> Change password

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#67]
Change password button not working

![Screenshot_20231227_162402](https://github.com/antonym8/Team-app/assets/142376069/f1944cfb-5da8-4888-944d-f6c16087f072)

**Comment by m8brindakumar** [comment]
its fixed

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
https://github.com/antonym8/Team-app/assets/142376069/98a86a2b-ebd2-46af-bf3f-82ea3c18762c
