### ISSUE TITLE
Active / Inactive volunteer 

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#68]
Status changed but multiple popups opened and in background loading icon displayed

https://github.com/antonym8/Team-app/assets/142376069/8ccf3f00-05a4-4366-aae7-e34f2954ff59

**Comment by m8brindakumar** [comment]
Its working

**Comment by antonym8** [comment]
https://github.com/antonym8/Team-app/assets/142376069/c8d09f97-2759-4799-b4cb-2e89684ab8c4
