### ISSUE TITLE
Add volunteer -> Password field

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#7]
Password field looks like a text field. When type password it should not visible to user after clicking on the eye icon only it should visible to user

![Screenshot_20231130_170135](https://github.com/antonym8/Team-app/assets/142376069/2fd1b107-e169-4d83-aa46-fd95031df353)

**Comment by m8brindakumar** [comment]
ok, but this is password creation field admin only create the password .

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
![Screenshot_20231229_124216](https://github.com/antonym8/Team-app/assets/142376069/3b969ef2-287f-4e21-8ac3-bd4b3b5d061e)
