### ISSUE TITLE
Add party with existing name

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#70]
Party created with existing name

![Screenshot_20231229_111008](https://github.com/antonym8/Team-app/assets/142376069/45ecfb38-4f74-4d43-bba4-ce2b3a84a319)

**Comment by SoundharSm8** [comment]
@antonym8  Duplicate wont create. Fixed

**Comment by antonym8** [comment]
@SoundharSm8 Proper message should display now it's showing validation error

![Screenshot_20240111_130449](https://github.com/antonym8/Team-app/assets/142376069/ffddfd88-6b0a-473d-9cc5-d0c7662a4d55)

**Comment by m8brindakumar** [comment]
message changed.

**Comment by antonym8** [comment]
In edit it's still showing the "Validation error" message and acronym field accepts the duplicate value

![Screenshot_20240123_104952](https://github.com/antonym8/Team-app/assets/142376069/cfa4858b-0fe7-4dda-8d9d-8ef0f1bca9fd)

**Comment by m8brindakumar** [comment]
Fixed
