### ISSUE TITLE
Edit party 

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#71]
Updated successfully message displayed but data not updated and after edit page redirected to whatsapp template page

https://github.com/antonym8/Team-app/assets/142376069/2a304cfd-17fa-445d-a4c9-e4aadbc74597

**Comment by m8brindakumar** [comment]
its already fixed, working properly

**Comment by m8brindakumar** [comment]
its already fixed, working properly

**Comment by antonym8** [comment]
https://github.com/antonym8/Team-app/assets/142376069/0da33ded-d86b-4ba6-bfe3-e18ea676d821
