### ISSUE TITLE
Add voter type with blank data

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#72]
No validation message displayed when add voter type with blank data

https://github.com/antonym8/Team-app/assets/142376069/9b4cb1d6-6dce-4d59-bf09-b2894ab7ed92

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
![Screenshot_20240111_153654](https://github.com/antonym8/Team-app/assets/142376069/4a7245ad-f4af-4df3-b2dc-84b9533b4eb0)
