### ISSUE TITLE
Add voter type with existing name

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#73]
New voter type created with existing name

![Screenshot_20231229_111929](https://github.com/antonym8/Team-app/assets/142376069/d3b68451-8131-477e-9167-7e49d62279a2)

**Comment by SoundharSm8** [comment]
@antonym8  Duplicate wont create. Fixed

**Comment by antonym8** [comment]
![Screenshot_20240111_153802](https://github.com/antonym8/Team-app/assets/142376069/3fc8558a-0815-434a-b4d0-14e625bfba1d)
