### ISSUE TITLE
Add SMS template with existing name

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#75]
New SMS template created with existing name

![Screenshot_20231229_122340](https://github.com/antonym8/Team-app/assets/142376069/0691514a-f37f-43c2-a03f-85217d7dcec3)

**Comment by SoundharSm8** [comment]
@antonym8  Now duplicate name wont be created

**Comment by SoundharSm8** [comment]
@antonym8  Fixed

**Comment by antonym8** [comment]
![Screenshot_20240111_153952](https://github.com/antonym8/Team-app/assets/142376069/f889edcc-16e7-4fe3-9bd4-433e5b460dd4)
