### ISSUE TITLE
Add whatsapp template with existing name

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#76]
New whatsapp template created

![Screenshot_20231229_122627](https://github.com/antonym8/Team-app/assets/142376069/a27a08de-0435-4ef7-8fef-43eb86ebd65d)

**Comment by SoundharSm8** [comment]
@antonym8  Duplicate wont created. Fixed

**Comment by antonym8** [comment]
![Screenshot_20240111_154218](https://github.com/antonym8/Team-app/assets/142376069/e8ee2943-97ae-43a7-8c82-c54850ddc069)
