### ISSUE TITLE
Whatsapp template -> Import from library

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#77]
Import from library button not working

![Screenshot_20231229_122627](https://github.com/antonym8/Team-app/assets/142376069/b933559b-15f1-429a-9355-9695caf70497)

**Comment by m8brindakumar** [comment]
its removed by this page because some clarification on into this page.

**Comment by antonym8** [comment]
![Screenshot_20240123_121425](https://github.com/antonym8/Team-app/assets/142376069/78dee3ec-06fd-4318-b557-a7185811e760)
