### ISSUE TITLE
Voice call template -> Not able to add the audio file

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#78]
Not able to add the audio file

![Screenshot_20231229_123403](https://github.com/antonym8/Team-app/assets/142376069/15243589-68c9-4d33-b516-68b6c2a51828)

**Comment by m8brindakumar** [comment]
its working

**Comment by antonym8** [comment]
File uploaded location displayed

![Screenshot_20240123_121558](https://github.com/antonym8/Team-app/assets/142376069/89cc398e-f9c7-4fbf-8043-9f54d3e40d48)

**Comment by m8brindakumar** [comment]
fixed

**Comment by m8brindakumar** [comment]
its working
