### ISSUE TITLE
Add audio file error message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#79]
Error message showing "Check / Add image" But it should be "Check / Add audio"

![Screenshot_20231229_123159](https://github.com/antonym8/Team-app/assets/142376069/7e77eebf-725b-440c-8a88-5320b9a77cd2)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
![Screenshot_20240111_154352](https://github.com/antonym8/Team-app/assets/142376069/d565f552-c405-4c9c-8099-e98e86b6088e)
