### ISSUE TITLE
Survey -> Static booth number

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#82]
Booth no showing static number

![Screenshot_20240112_163228](https://github.com/antonym8/Team-app/assets/142376069/93aa1ad2-2ae6-494d-911a-0a3785bec755)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
![Screenshot_20240123_122022](https://github.com/antonym8/Team-app/assets/142376069/16092480-847f-47f1-9b50-832b7bac689b)
