### ISSUE TITLE
Religion -> Spelling mistake in choose

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#86]
![Screenshot_20240112_163228](https://github.com/antonym8/Team-app/assets/142376069/17f5811b-93f6-4fc9-8f25-c905eb6b60ec)

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
![Screenshot_20240123_122226](https://github.com/antonym8/Team-app/assets/142376069/59475f37-db2e-4b66-9ec8-bc9fff7a067d)
