### ISSUE TITLE
Choose caste showing the heading "Religion"

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#88]
![Screenshot_20240112_164317](https://github.com/antonym8/Team-app/assets/142376069/09d9e1a2-5bfe-4ac9-b435-e254d8d1b68a)

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
![Screenshot_20240123_122348](https://github.com/antonym8/Team-app/assets/142376069/e6e18632-127a-4c2e-82b1-663d09b35ba6)
