### ISSUE TITLE
Update password without enter current password

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#90]
Error message should display when update the password without enter the current password

https://github.com/antonym8/Team-app/assets/142376069/2fa68439-fdeb-4803-8d4c-7efc7e17a690

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
Error message displayed in wrong field

![Screenshot_20240201_182338](https://github.com/antonym8/Team-app/assets/142376069/817ebf07-e405-4b0f-bba4-3e137971746b)

**Comment by m8brindakumar** [comment]
fixed
