### ISSUE TITLE
Booth numbers and booth data

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#96]
Select booth page showing wrong booth number and all booth's are showing incorrect datas

![Screenshot_20240122_184328](https://github.com/antonym8/Team-app/assets/142376069/67bbc970-2f11-47f7-b096-d22d7d3b5e3d)

**Comment by m8brindakumar** [comment]
its working

**Comment by antonym8** [comment]
In campaign booth number showing as 1, 2, 3, ... and in other pages it shows as 40, 48, ...

https://github.com/antonym8/Team-app/assets/142376069/d5170684-e23e-4d71-859f-f3cb7e8c04a2

**Comment by m8brindakumar** [comment]
Fixed
